### ISSUE TITLE
be able to run

### ISSUE THREAD

**Issue by ossadtchi** [kuznesashka/Wave_prior_inverse#2]
In order to run the code I need the external files. It is generally not practiced to store large files in the repositories as it would take ages to resynch. A way to resolve this is to add instructions to readme.md and point to a cloud where the needed files are. Perhaps there is a better solution offered by github, please, find out.

**Comment by ossadtchi** [comment]
See the last solution here
https://towardsdatascience.com/uploading-large-files-to-github-dbef518fa1a

**Comment by kuznesashka** [comment]
Updated Readme file with Google folder link.
