### ISSUE TITLE
known wave origin

### ISSUE THREAD

**Issue by ossadtchi** [kuznesashka/Wave_prior_inverse#3]
In the simulations you assumed that you know exactly where the wave is coming from. This is not the case usually as we fit dipoles to the peak and this will cause error. To avoid a full blown inverse model solving you can simulate these localization errors by doing MC and adding random jitter to the wave origin based on the Gaussian distribution with std.dev of about 2 мм.

**Comment by kuznesashka** [comment]
Added the <= 2mm error to the initial point

**Comment by kuznesashka** [comment]
Added the <= 2mm error to the initial point
